-- Generated by `npm run db:generate-seed` from src/lib/data.ts.
-- Do not edit by hand. Safe to re-run: uses ON CONFLICT DO UPDATE.

insert into public.stores (
      id, name, slug, area, address, phone, rating, review_count,
      open_hours, pickup_instructions, image_url, banner_image_url, lat, lng, is_active
    ) values (
      'store_grand_square', 'Grand Square Supermarket & Bakery', 'grand-square-central-area', 'Central Area',
      'Plot 272, Central Business District, Mohammadu Buhari Way, Abuja', '+234 803 900 1122', 4.8, 342,
      '8:00 AM – 9:00 PM (Daily)', 'Pick up in person or send a dispatch rider. Present your order number SG-XXXXX and 4-digit PIN at the customer care desk.', 'https://images.unsplash.com/photo-1578916171728-46686eac8d58?auto=format&fit=crop&w=800&q=80',
      'https://images.unsplash.com/photo-1542838132-92c53300491e?auto=format&fit=crop&w=1200&q=80', 9.0578, 7.4951,
      true
    )
    on conflict (id) do update set
      name = excluded.name,
      slug = excluded.slug,
      area = excluded.area,
      address = excluded.address,
      phone = excluded.phone,
      rating = excluded.rating,
      review_count = excluded.review_count,
      open_hours = excluded.open_hours,
      pickup_instructions = excluded.pickup_instructions,
      image_url = excluded.image_url,
      banner_image_url = excluded.banner_image_url,
      lat = excluded.lat,
      lng = excluded.lng,
      is_active = excluded.is_active,
      updated_at = now();

insert into public.stores (
      id, name, slug, area, address, phone, rating, review_count,
      open_hours, pickup_instructions, image_url, banner_image_url, lat, lng, is_active
    ) values (
      'store_h_medix', 'H-Medix Pharmacy & Supermarket', 'h-medix-wuse-2', 'Wuse II',
      '43 Ademola Adetokunbo Crescent, Wuse II, Abuja', '+234 802 444 8899', 4.9, 520,
      '8:00 AM – 10:00 PM (Daily)', 'Pick up in person or send a dispatch rider. Present your order number SG-XXXXX and 4-digit PIN at the customer care desk.', 'https://images.unsplash.com/photo-1583258292688-d0213dc5a3a8?auto=format&fit=crop&w=800&q=80',
      'https://images.unsplash.com/photo-1579113800032-c38bd7635818?auto=format&fit=crop&w=1200&q=80', 9.0772, 7.4812,
      true
    )
    on conflict (id) do update set
      name = excluded.name,
      slug = excluded.slug,
      area = excluded.area,
      address = excluded.address,
      phone = excluded.phone,
      rating = excluded.rating,
      review_count = excluded.review_count,
      open_hours = excluded.open_hours,
      pickup_instructions = excluded.pickup_instructions,
      image_url = excluded.image_url,
      banner_image_url = excluded.banner_image_url,
      lat = excluded.lat,
      lng = excluded.lng,
      is_active = excluded.is_active,
      updated_at = now();

insert into public.stores (
      id, name, slug, area, address, phone, rating, review_count,
      open_hours, pickup_instructions, image_url, banner_image_url, lat, lng, is_active
    ) values (
      'store_next_cash_carry', 'Next Cash & Carry Mega Supermarket', 'next-cash-carry-jahi', 'Jahi',
      'Ahmadu Bello Way, Jahi/Kado District, Abuja', '+234 818 777 0011', 4.7, 890,
      '9:00 AM – 8:30 PM (Daily)', 'Pick up in person or send a dispatch rider. Present your order number SG-XXXXX and 4-digit PIN at Entrance B online pickup desk.', 'https://images.unsplash.com/photo-1534723452862-4c874018d66d?auto=format&fit=crop&w=800&q=80',
      'https://images.unsplash.com/photo-1506484381205-f7945653044d?auto=format&fit=crop&w=1200&q=80', 9.0911, 7.4328,
      true
    )
    on conflict (id) do update set
      name = excluded.name,
      slug = excluded.slug,
      area = excluded.area,
      address = excluded.address,
      phone = excluded.phone,
      rating = excluded.rating,
      review_count = excluded.review_count,
      open_hours = excluded.open_hours,
      pickup_instructions = excluded.pickup_instructions,
      image_url = excluded.image_url,
      banner_image_url = excluded.banner_image_url,
      lat = excluded.lat,
      lng = excluded.lng,
      is_active = excluded.is_active,
      updated_at = now();

insert into public.stores (
      id, name, slug, area, address, phone, rating, review_count,
      open_hours, pickup_instructions, image_url, banner_image_url, lat, lng, is_active
    ) values (
      'store_4u', '4U Supermarket (formerly Amigo)', '4u-supermarket-wuse-2', 'Wuse II',
      '54 Aminu Kano Crescent, Wuse II, Abuja', '+234 809 123 4567', 4.6, 410,
      '8:30 AM – 9:30 PM (Daily)', 'Pick up in person or send a dispatch rider. Present your order number SG-XXXXX and 4-digit PIN at the customer care desk.', 'https://images.unsplash.com/photo-1588964895597-cfccd6e2dbf9?auto=format&fit=crop&w=800&q=80',
      'https://images.unsplash.com/photo-1526367790999-0150786686a2?auto=format&fit=crop&w=1200&q=80', 9.0715, 7.4789,
      true
    )
    on conflict (id) do update set
      name = excluded.name,
      slug = excluded.slug,
      area = excluded.area,
      address = excluded.address,
      phone = excluded.phone,
      rating = excluded.rating,
      review_count = excluded.review_count,
      open_hours = excluded.open_hours,
      pickup_instructions = excluded.pickup_instructions,
      image_url = excluded.image_url,
      banner_image_url = excluded.banner_image_url,
      lat = excluded.lat,
      lng = excluded.lng,
      is_active = excluded.is_active,
      updated_at = now();

insert into public.stores (
      id, name, slug, area, address, phone, rating, review_count,
      open_hours, pickup_instructions, image_url, banner_image_url, lat, lng, is_active
    ) values (
      'store_sahad', 'Sahad Stores', 'sahad-stores-central-area', 'Central Area',
      'Area 11, Off Tafawa Balewa Way, Central Business District, Abuja', '+234 803 555 9900', 4.7, 630,
      '8:30 AM – 8:00 PM (Daily)', 'Pick up in person or send a dispatch rider. Present your order number SG-XXXXX and 4-digit PIN at the ground floor exit desk.', 'https://images.unsplash.com/photo-1604719312566-8912e9227c6a?auto=format&fit=crop&w=800&q=80',
      'https://images.unsplash.com/photo-1578916171728-46686eac8d58?auto=format&fit=crop&w=1200&q=80', 9.0512, 7.4891,
      true
    )
    on conflict (id) do update set
      name = excluded.name,
      slug = excluded.slug,
      area = excluded.area,
      address = excluded.address,
      phone = excluded.phone,
      rating = excluded.rating,
      review_count = excluded.review_count,
      open_hours = excluded.open_hours,
      pickup_instructions = excluded.pickup_instructions,
      image_url = excluded.image_url,
      banner_image_url = excluded.banner_image_url,
      lat = excluded.lat,
      lng = excluded.lng,
      is_active = excluded.is_active,
      updated_at = now();

insert into public.stores (
      id, name, slug, area, address, phone, rating, review_count,
      open_hours, pickup_instructions, image_url, banner_image_url, lat, lng, is_active
    ) values (
      'store_market_square', 'Market Square Supermarket', 'market-square-jabi', 'Jabi',
      'Jabi Lake Mall, Bala Sokoto Way, Jabi, Abuja', '+234 814 333 2211', 4.8, 290,
      '9:00 AM – 9:00 PM (Daily)', 'Pick up in person or send a dispatch rider. Present your order number SG-XXXXX and 4-digit PIN at the customer care desk.', 'https://images.unsplash.com/photo-1543083477-4f785aeafaa9?auto=format&fit=crop&w=800&q=80',
      'https://images.unsplash.com/photo-1542838132-92c53300491e?auto=format&fit=crop&w=1200&q=80', 9.0745, 7.429,
      true
    )
    on conflict (id) do update set
      name = excluded.name,
      slug = excluded.slug,
      area = excluded.area,
      address = excluded.address,
      phone = excluded.phone,
      rating = excluded.rating,
      review_count = excluded.review_count,
      open_hours = excluded.open_hours,
      pickup_instructions = excluded.pickup_instructions,
      image_url = excluded.image_url,
      banner_image_url = excluded.banner_image_url,
      lat = excluded.lat,
      lng = excluded.lng,
      is_active = excluded.is_active,
      updated_at = now();

insert into public.categories (
      id, name, slug, icon, description, item_count, gradient, bg_light
    ) values (
      'cat_dairy_eggs', 'Dairy & Eggs', 'dairy-eggs', 'Milk',
      'Fresh milk, Greek yogurts, imported cheeses, butter, and farm eggs.', 16, 'from-sky-500/20 to-blue-600/10',
      'bg-sky-50 text-sky-700 border-sky-200'
    )
    on conflict (id) do update set
      name = excluded.name,
      slug = excluded.slug,
      icon = excluded.icon,
      description = excluded.description,
      item_count = excluded.item_count,
      gradient = excluded.gradient,
      bg_light = excluded.bg_light;

insert into public.categories (
      id, name, slug, icon, description, item_count, gradient, bg_light
    ) values (
      'cat_bakery', 'Bakery & Bread', 'bakery-bread', 'Croissant',
      'Artisan sourdough, sliced toast, butter croissants, and brioche rolls.', 12, 'from-amber-500/20 to-orange-600/10',
      'bg-amber-50 text-amber-700 border-amber-200'
    )
    on conflict (id) do update set
      name = excluded.name,
      slug = excluded.slug,
      icon = excluded.icon,
      description = excluded.description,
      item_count = excluded.item_count,
      gradient = excluded.gradient,
      bg_light = excluded.bg_light;

insert into public.categories (
      id, name, slug, icon, description, item_count, gradient, bg_light
    ) values (
      'cat_pantry', 'Pantry & Grains', 'pantry-grains', 'Wheat',
      'Premium basmati rice, Italian pasta, oat flakes, cereals, and flour.', 28, 'from-emerald-500/20 to-teal-600/10',
      'bg-emerald-50 text-emerald-700 border-emerald-200'
    )
    on conflict (id) do update set
      name = excluded.name,
      slug = excluded.slug,
      icon = excluded.icon,
      description = excluded.description,
      item_count = excluded.item_count,
      gradient = excluded.gradient,
      bg_light = excluded.bg_light;

insert into public.categories (
      id, name, slug, icon, description, item_count, gradient, bg_light
    ) values (
      'cat_beverages', 'Beverages & Juices', 'beverages-juices', 'Coffee',
      'Pure pressed juices, malt drinks, organic teas, ground coffee, and iced tea.', 22, 'from-purple-500/20 to-indigo-600/10',
      'bg-purple-50 text-purple-700 border-purple-200'
    )
    on conflict (id) do update set
      name = excluded.name,
      slug = excluded.slug,
      icon = excluded.icon,
      description = excluded.description,
      item_count = excluded.item_count,
      gradient = excluded.gradient,
      bg_light = excluded.bg_light;

insert into public.categories (
      id, name, slug, icon, description, item_count, gradient, bg_light
    ) values (
      'cat_snacks', 'Snacks & Treats', 'snacks-treats', 'Cookie',
      'Imported chocolates, potato crisps, roasted cashews, biscuits, and energy bars.', 19, 'from-rose-500/20 to-pink-600/10',
      'bg-rose-50 text-rose-700 border-rose-200'
    )
    on conflict (id) do update set
      name = excluded.name,
      slug = excluded.slug,
      icon = excluded.icon,
      description = excluded.description,
      item_count = excluded.item_count,
      gradient = excluded.gradient,
      bg_light = excluded.bg_light;

insert into public.categories (
      id, name, slug, icon, description, item_count, gradient, bg_light
    ) values (
      'cat_canned', 'Canned & Preserved', 'canned-preserved', 'Package',
      'Sardines in olive oil, sweetcorn, baked beans, corned beef, and peeled plum tomatoes.', 14, 'from-yellow-500/20 to-amber-600/10',
      'bg-yellow-50 text-yellow-800 border-yellow-200'
    )
    on conflict (id) do update set
      name = excluded.name,
      slug = excluded.slug,
      icon = excluded.icon,
      description = excluded.description,
      item_count = excluded.item_count,
      gradient = excluded.gradient,
      bg_light = excluded.bg_light;

insert into public.categories (
      id, name, slug, icon, description, item_count, gradient, bg_light
    ) values (
      'cat_condiments', 'Sauces & Spreads', 'sauces-spreads', 'Flame',
      'Extra virgin olive oil, creamy mayonnaise, peanut butter, pasta sauces, and honey.', 15, 'from-red-500/20 to-orange-600/10',
      'bg-red-50 text-red-700 border-red-200'
    )
    on conflict (id) do update set
      name = excluded.name,
      slug = excluded.slug,
      icon = excluded.icon,
      description = excluded.description,
      item_count = excluded.item_count,
      gradient = excluded.gradient,
      bg_light = excluded.bg_light;

insert into public.categories (
      id, name, slug, icon, description, item_count, gradient, bg_light
    ) values (
      'cat_frozen', 'Frozen & Chilled', 'frozen-chilled', 'Snowflake',
      'Premium frozen chicken fillets, gourmet sausages, berry mix, and ice cream.', 11, 'from-cyan-500/20 to-blue-600/10',
      'bg-cyan-50 text-cyan-700 border-cyan-200'
    )
    on conflict (id) do update set
      name = excluded.name,
      slug = excluded.slug,
      icon = excluded.icon,
      description = excluded.description,
      item_count = excluded.item_count,
      gradient = excluded.gradient,
      bg_light = excluded.bg_light;

insert into public.products (
      id, name, brand, slug, category_id, store_id, description, unit, images,
      original_price, base_discount_percent, date_type, expiry_date, listed_at,
      drift_rate_weekly, stock_quantity, featured, storage_condition,
      nafdac_reg_no, condition_notes, nutritional_highlights
    ) values (
      'sg_prod_001', 'Peak Full Cream Milk Powder (Refill Pack)', 'Peak Milk', 'peak-full-cream-milk-powder-850g',
      'cat_dairy_eggs', 'store_grand_square', 'Rich, creamy 850g refill pouch fortified with 28 essential vitamins and minerals. Perfect for daily tea, coffee, breakfast cereal, and baking.',
      '850g Pouch', ARRAY['https://images.unsplash.com/photo-1550583724-b2692b85b150?auto=format&fit=crop&w=800&q=80']::text[], 8500,
      35, 'best_before', '2026-09-12',
      '2026-08-18', 0.025, 9,
      true, 'ambient', '01-0024',
      'Factory sealed, outer cardboard outer box slightly creased.', ARRAY['Fortified with Vitamin A & D', 'Rich Calcium Source', '28g Protein per 100g']::text[]
    )
    on conflict (id) do update set
      name = excluded.name,
      brand = excluded.brand,
      slug = excluded.slug,
      category_id = excluded.category_id,
      store_id = excluded.store_id,
      description = excluded.description,
      unit = excluded.unit,
      images = excluded.images,
      original_price = excluded.original_price,
      base_discount_percent = excluded.base_discount_percent,
      date_type = excluded.date_type,
      expiry_date = excluded.expiry_date,
      listed_at = excluded.listed_at,
      drift_rate_weekly = excluded.drift_rate_weekly,
      stock_quantity = excluded.stock_quantity,
      featured = excluded.featured,
      storage_condition = excluded.storage_condition,
      nafdac_reg_no = excluded.nafdac_reg_no,
      condition_notes = excluded.condition_notes,
      nutritional_highlights = excluded.nutritional_highlights,
      updated_at = now();

insert into public.products (
      id, name, brand, slug, category_id, store_id, description, unit, images,
      original_price, base_discount_percent, date_type, expiry_date, listed_at,
      drift_rate_weekly, stock_quantity, featured, storage_condition,
      nafdac_reg_no, condition_notes, nutritional_highlights
    ) values (
      'sg_prod_002', 'Kellogg''s Corn Flakes Original Family Pack', 'Kellogg''s', 'kelloggs-corn-flakes-750g',
      'cat_pantry', 'store_h_medix', 'Crispy, golden toasted corn flakes made from sun-ripened corn. Iron and B-vitamin rich morning fuel for the entire family.',
      '750g Box', ARRAY['https://images.unsplash.com/photo-1586201375761-83865001e31c?auto=format&fit=crop&w=800&q=80']::text[], 6200,
      40, 'best_before', '2026-09-08',
      '2026-08-11', 0.025, 5,
      true, 'ambient', '01-1456',
      'Pristine inner foil seal intact.', ARRAY['High Iron', 'Vitamin B1, B2, B3, B6, B12', 'Low Fat']::text[]
    )
    on conflict (id) do update set
      name = excluded.name,
      brand = excluded.brand,
      slug = excluded.slug,
      category_id = excluded.category_id,
      store_id = excluded.store_id,
      description = excluded.description,
      unit = excluded.unit,
      images = excluded.images,
      original_price = excluded.original_price,
      base_discount_percent = excluded.base_discount_percent,
      date_type = excluded.date_type,
      expiry_date = excluded.expiry_date,
      listed_at = excluded.listed_at,
      drift_rate_weekly = excluded.drift_rate_weekly,
      stock_quantity = excluded.stock_quantity,
      featured = excluded.featured,
      storage_condition = excluded.storage_condition,
      nafdac_reg_no = excluded.nafdac_reg_no,
      condition_notes = excluded.condition_notes,
      nutritional_highlights = excluded.nutritional_highlights,
      updated_at = now();

insert into public.products (
      id, name, brand, slug, category_id, store_id, description, unit, images,
      original_price, base_discount_percent, date_type, expiry_date, listed_at,
      drift_rate_weekly, stock_quantity, featured, storage_condition,
      nafdac_reg_no, condition_notes, nutritional_highlights
    ) values (
      'sg_prod_003', 'Nutella Hazelnut Spread with Cocoa', 'Ferrero', 'nutella-hazelnut-spread-750g',
      'cat_condiments', 'store_next_cash_carry', 'Iconic creamy spread made with selected roasted hazelnuts and skimmed milk. Heavenly on toasted bread, pancakes, or fruit slices.',
      '750g Glass Jar', ARRAY['https://images.unsplash.com/photo-1590080875515-8a3a8dc5735e?auto=format&fit=crop&w=800&q=80']::text[], 9800,
      45, 'best_before', '2026-09-06',
      '2026-08-04', 0.025, 3,
      true, 'ambient', '01-7890',
      'Gold foil under lid 100% factory sealed.', ARRAY['No Artificial Colors', 'No Preservatives', 'Real Hazelnuts']::text[]
    )
    on conflict (id) do update set
      name = excluded.name,
      brand = excluded.brand,
      slug = excluded.slug,
      category_id = excluded.category_id,
      store_id = excluded.store_id,
      description = excluded.description,
      unit = excluded.unit,
      images = excluded.images,
      original_price = excluded.original_price,
      base_discount_percent = excluded.base_discount_percent,
      date_type = excluded.date_type,
      expiry_date = excluded.expiry_date,
      listed_at = excluded.listed_at,
      drift_rate_weekly = excluded.drift_rate_weekly,
      stock_quantity = excluded.stock_quantity,
      featured = excluded.featured,
      storage_condition = excluded.storage_condition,
      nafdac_reg_no = excluded.nafdac_reg_no,
      condition_notes = excluded.condition_notes,
      nutritional_highlights = excluded.nutritional_highlights,
      updated_at = now();

insert into public.products (
      id, name, brand, slug, category_id, store_id, description, unit, images,
      original_price, base_discount_percent, date_type, expiry_date, listed_at,
      drift_rate_weekly, stock_quantity, featured, storage_condition,
      nafdac_reg_no, condition_notes, nutritional_highlights
    ) values (
      'sg_prod_004', 'Barilla Spaghetti No. 5 (Pack of 3)', 'Barilla', 'barilla-spaghetti-pack-of-3',
      'cat_pantry', 'store_4u', 'Authentic Italian durum wheat semolina pasta that holds al dente texture every time. Bundle of 3 x 500g boxes.',
      '3 x 500g Pack', ARRAY['https://images.unsplash.com/photo-1621996346565-e3d5d6281691?auto=format&fit=crop&w=800&q=80']::text[], 7500,
      30, 'best_before', '2026-09-25',
      '2026-08-20', 0.025, 14,
      false, 'ambient', '01-4432',
      'Original imported packaging, perfect condition.', ARRAY['100% Durum Semolina', 'Non-GMO Project Verified', '12g Protein']::text[]
    )
    on conflict (id) do update set
      name = excluded.name,
      brand = excluded.brand,
      slug = excluded.slug,
      category_id = excluded.category_id,
      store_id = excluded.store_id,
      description = excluded.description,
      unit = excluded.unit,
      images = excluded.images,
      original_price = excluded.original_price,
      base_discount_percent = excluded.base_discount_percent,
      date_type = excluded.date_type,
      expiry_date = excluded.expiry_date,
      listed_at = excluded.listed_at,
      drift_rate_weekly = excluded.drift_rate_weekly,
      stock_quantity = excluded.stock_quantity,
      featured = excluded.featured,
      storage_condition = excluded.storage_condition,
      nafdac_reg_no = excluded.nafdac_reg_no,
      condition_notes = excluded.condition_notes,
      nutritional_highlights = excluded.nutritional_highlights,
      updated_at = now();

insert into public.products (
      id, name, brand, slug, category_id, store_id, description, unit, images,
      original_price, base_discount_percent, date_type, expiry_date, listed_at,
      drift_rate_weekly, stock_quantity, featured, storage_condition,
      nafdac_reg_no, condition_notes, nutritional_highlights
    ) values (
      'sg_prod_005', 'Chi Exotic Pineapple & Coconut Nectar', 'Chi', 'chi-exotic-pineapple-coconut-1l',
      'cat_beverages', 'store_grand_square', 'Tropical island fusion of luscious pineapple juice with refreshing creamy coconut extract in 1-Litre Tetra Pak.',
      '1L Tetra Pak', ARRAY['https://images.unsplash.com/photo-1546173159-315724a31696?auto=format&fit=crop&w=800&q=80']::text[], 1900,
      35, 'best_before', '2026-09-10',
      '2026-08-15', 0.025, 20,
      false, 'ambient', '01-2289',
      'Refrigerate once opened.', ARRAY['Natural Fruit Sugars', 'Vitamin C Enriched']::text[]
    )
    on conflict (id) do update set
      name = excluded.name,
      brand = excluded.brand,
      slug = excluded.slug,
      category_id = excluded.category_id,
      store_id = excluded.store_id,
      description = excluded.description,
      unit = excluded.unit,
      images = excluded.images,
      original_price = excluded.original_price,
      base_discount_percent = excluded.base_discount_percent,
      date_type = excluded.date_type,
      expiry_date = excluded.expiry_date,
      listed_at = excluded.listed_at,
      drift_rate_weekly = excluded.drift_rate_weekly,
      stock_quantity = excluded.stock_quantity,
      featured = excluded.featured,
      storage_condition = excluded.storage_condition,
      nafdac_reg_no = excluded.nafdac_reg_no,
      condition_notes = excluded.condition_notes,
      nutritional_highlights = excluded.nutritional_highlights,
      updated_at = now();

insert into public.products (
      id, name, brand, slug, category_id, store_id, description, unit, images,
      original_price, base_discount_percent, date_type, expiry_date, listed_at,
      drift_rate_weekly, stock_quantity, featured, storage_condition,
      nafdac_reg_no, condition_notes, nutritional_highlights
    ) values (
      'sg_prod_006', 'Lurpak Slightly Salted Danish Butter', 'Lurpak', 'lurpak-slightly-salted-butter-200g',
      'cat_dairy_eggs', 'store_h_medix', 'Legendary Danish churned butter made from fresh cream. Unmistakably rich taste with just a pinch of salt.',
      '200g Foil Block', ARRAY['https://images.unsplash.com/photo-1589985270826-4b7bb135bc9d?auto=format&fit=crop&w=800&q=80']::text[], 4200,
      50, 'use_by', '2026-09-05',
      '2026-08-01', 0.025, 4,
      true, 'chilled', '01-9011',
      'Continuous chilled storage maintained at H-Medix Wuse II.', ARRAY['100% Pure Danish Cream', 'No Palm Oil']::text[]
    )
    on conflict (id) do update set
      name = excluded.name,
      brand = excluded.brand,
      slug = excluded.slug,
      category_id = excluded.category_id,
      store_id = excluded.store_id,
      description = excluded.description,
      unit = excluded.unit,
      images = excluded.images,
      original_price = excluded.original_price,
      base_discount_percent = excluded.base_discount_percent,
      date_type = excluded.date_type,
      expiry_date = excluded.expiry_date,
      listed_at = excluded.listed_at,
      drift_rate_weekly = excluded.drift_rate_weekly,
      stock_quantity = excluded.stock_quantity,
      featured = excluded.featured,
      storage_condition = excluded.storage_condition,
      nafdac_reg_no = excluded.nafdac_reg_no,
      condition_notes = excluded.condition_notes,
      nutritional_highlights = excluded.nutritional_highlights,
      updated_at = now();

insert into public.products (
      id, name, brand, slug, category_id, store_id, description, unit, images,
      original_price, base_discount_percent, date_type, expiry_date, listed_at,
      drift_rate_weekly, stock_quantity, featured, storage_condition,
      nafdac_reg_no, condition_notes, nutritional_highlights
    ) values (
      'sg_prod_007', 'Titus Sardines in Pure Vegetable Oil (Pack of 5)', 'Titus', 'titus-sardines-pack-of-5',
      'cat_canned', 'store_sahad', 'Classic wild-caught Atlantic sardines packed with heart-healthy Omega-3 fatty acids and protein. Bundle of 5 cans with easy pull-tab.',
      '5 x 125g Cans', ARRAY['https://images.unsplash.com/photo-1534483509719-3feaee7c30da?auto=format&fit=crop&w=800&q=80']::text[], 6500,
      30, 'best_before', '2026-09-30',
      '2026-08-25', 0.025, 18,
      false, 'ambient', '01-0088',
      'Undamaged cans, zero denting.', ARRAY['High Omega-3', '22g Protein per can', 'Calcium Rich']::text[]
    )
    on conflict (id) do update set
      name = excluded.name,
      brand = excluded.brand,
      slug = excluded.slug,
      category_id = excluded.category_id,
      store_id = excluded.store_id,
      description = excluded.description,
      unit = excluded.unit,
      images = excluded.images,
      original_price = excluded.original_price,
      base_discount_percent = excluded.base_discount_percent,
      date_type = excluded.date_type,
      expiry_date = excluded.expiry_date,
      listed_at = excluded.listed_at,
      drift_rate_weekly = excluded.drift_rate_weekly,
      stock_quantity = excluded.stock_quantity,
      featured = excluded.featured,
      storage_condition = excluded.storage_condition,
      nafdac_reg_no = excluded.nafdac_reg_no,
      condition_notes = excluded.condition_notes,
      nutritional_highlights = excluded.nutritional_highlights,
      updated_at = now();

insert into public.products (
      id, name, brand, slug, category_id, store_id, description, unit, images,
      original_price, base_discount_percent, date_type, expiry_date, listed_at,
      drift_rate_weekly, stock_quantity, featured, storage_condition,
      nafdac_reg_no, condition_notes, nutritional_highlights
    ) values (
      'sg_prod_008', 'Grand Square Fresh Brioche Burger Buns (6-Pack)', 'Grand Square In-House Bakery', 'grand-square-brioche-burger-buns-6pack',
      'cat_bakery', 'store_grand_square', 'Golden, buttery, glazed French brioche burger buns baked daily in-store. Pillowy soft crumb that toasts to perfection.',
      'Pack of 6 Buns', ARRAY['https://images.unsplash.com/photo-1509440159596-0249088772ff?auto=format&fit=crop&w=800&q=80']::text[], 3200,
      55, 'best_before', '2026-09-04',
      '2026-08-29', 0.025, 6,
      true, 'ambient', null,
      'Freshly bagged, best consumed or frozen within 3 days.', ARRAY['Pure Butter Glaze', 'Artisan Baked']::text[]
    )
    on conflict (id) do update set
      name = excluded.name,
      brand = excluded.brand,
      slug = excluded.slug,
      category_id = excluded.category_id,
      store_id = excluded.store_id,
      description = excluded.description,
      unit = excluded.unit,
      images = excluded.images,
      original_price = excluded.original_price,
      base_discount_percent = excluded.base_discount_percent,
      date_type = excluded.date_type,
      expiry_date = excluded.expiry_date,
      listed_at = excluded.listed_at,
      drift_rate_weekly = excluded.drift_rate_weekly,
      stock_quantity = excluded.stock_quantity,
      featured = excluded.featured,
      storage_condition = excluded.storage_condition,
      nafdac_reg_no = excluded.nafdac_reg_no,
      condition_notes = excluded.condition_notes,
      nutritional_highlights = excluded.nutritional_highlights,
      updated_at = now();

insert into public.products (
      id, name, brand, slug, category_id, store_id, description, unit, images,
      original_price, base_discount_percent, date_type, expiry_date, listed_at,
      drift_rate_weekly, stock_quantity, featured, storage_condition,
      nafdac_reg_no, condition_notes, nutritional_highlights
    ) values (
      'sg_prod_009', 'Heinz Classic Tomato Ketchup (Top Down)', 'Heinz', 'heinz-classic-tomato-ketchup-570g',
      'cat_condiments', 'store_next_cash_carry', 'Thick and rich tomato ketchup grown from Heinz signature seeds. Squeezable non-drip bottle.',
      '570g Squeeze Bottle', ARRAY['https://images.unsplash.com/photo-1527842891421-42eec6e703ea?auto=format&fit=crop&w=800&q=80']::text[], 4800,
      35, 'best_before', '2026-09-18',
      '2026-08-14', 0.025, 11,
      false, 'ambient', '01-5612',
      'Original factory seal intact.', ARRAY['No Artificial Flavors', 'Sun-Ripened Tomatoes']::text[]
    )
    on conflict (id) do update set
      name = excluded.name,
      brand = excluded.brand,
      slug = excluded.slug,
      category_id = excluded.category_id,
      store_id = excluded.store_id,
      description = excluded.description,
      unit = excluded.unit,
      images = excluded.images,
      original_price = excluded.original_price,
      base_discount_percent = excluded.base_discount_percent,
      date_type = excluded.date_type,
      expiry_date = excluded.expiry_date,
      listed_at = excluded.listed_at,
      drift_rate_weekly = excluded.drift_rate_weekly,
      stock_quantity = excluded.stock_quantity,
      featured = excluded.featured,
      storage_condition = excluded.storage_condition,
      nafdac_reg_no = excluded.nafdac_reg_no,
      condition_notes = excluded.condition_notes,
      nutritional_highlights = excluded.nutritional_highlights,
      updated_at = now();

insert into public.products (
      id, name, brand, slug, category_id, store_id, description, unit, images,
      original_price, base_discount_percent, date_type, expiry_date, listed_at,
      drift_rate_weekly, stock_quantity, featured, storage_condition,
      nafdac_reg_no, condition_notes, nutritional_highlights
    ) values (
      'sg_prod_010', 'Milo Energy Food Drink Powder (Refill Tin)', 'Nestlé', 'nestle-milo-energy-drink-1kg',
      'cat_beverages', 'store_sahad', 'Malted barley and cocoa beverage loaded with Activ-Go (Protomalt, 6 vitamins & 3 minerals) to give kids and adults winning energy.',
      '1kg Tin', ARRAY['https://images.unsplash.com/photo-1514432324607-a09d9b4aefdd?auto=format&fit=crop&w=800&q=80']::text[], 7900,
      38, 'best_before', '2026-09-15',
      '2026-08-10', 0.025, 8,
      true, 'ambient', '01-0005',
      'Vacuum sealed foil lid under tin cap.', ARRAY['Activ-Go Nutrient Complex', 'B-Vitamins for Energy Release']::text[]
    )
    on conflict (id) do update set
      name = excluded.name,
      brand = excluded.brand,
      slug = excluded.slug,
      category_id = excluded.category_id,
      store_id = excluded.store_id,
      description = excluded.description,
      unit = excluded.unit,
      images = excluded.images,
      original_price = excluded.original_price,
      base_discount_percent = excluded.base_discount_percent,
      date_type = excluded.date_type,
      expiry_date = excluded.expiry_date,
      listed_at = excluded.listed_at,
      drift_rate_weekly = excluded.drift_rate_weekly,
      stock_quantity = excluded.stock_quantity,
      featured = excluded.featured,
      storage_condition = excluded.storage_condition,
      nafdac_reg_no = excluded.nafdac_reg_no,
      condition_notes = excluded.condition_notes,
      nutritional_highlights = excluded.nutritional_highlights,
      updated_at = now();

insert into public.products (
      id, name, brand, slug, category_id, store_id, description, unit, images,
      original_price, base_discount_percent, date_type, expiry_date, listed_at,
      drift_rate_weekly, stock_quantity, featured, storage_condition,
      nafdac_reg_no, condition_notes, nutritional_highlights
    ) values (
      'sg_prod_011', 'Oreo Original Vanilla Creme Sandwich Cookies', 'Cadbury / Mondelez', 'oreo-original-vanilla-creme-family-pack',
      'cat_snacks', 'store_4u', 'The classic rich chocolate wafer cookies with a sweet vanilla creme center. Perfect for twisting, licking, and dunking in cold milk.',
      '345g Family Pack', ARRAY['https://images.unsplash.com/photo-1568051243851-f9b136146e97?auto=format&fit=crop&w=800&q=80']::text[], 3800,
      40, 'best_before', '2026-09-09',
      '2026-08-12', 0.025, 12,
      false, 'ambient', '01-3341',
      'Crisp and fresh.', ARRAY['Plant-Based Friendly', 'Real Cocoa']::text[]
    )
    on conflict (id) do update set
      name = excluded.name,
      brand = excluded.brand,
      slug = excluded.slug,
      category_id = excluded.category_id,
      store_id = excluded.store_id,
      description = excluded.description,
      unit = excluded.unit,
      images = excluded.images,
      original_price = excluded.original_price,
      base_discount_percent = excluded.base_discount_percent,
      date_type = excluded.date_type,
      expiry_date = excluded.expiry_date,
      listed_at = excluded.listed_at,
      drift_rate_weekly = excluded.drift_rate_weekly,
      stock_quantity = excluded.stock_quantity,
      featured = excluded.featured,
      storage_condition = excluded.storage_condition,
      nafdac_reg_no = excluded.nafdac_reg_no,
      condition_notes = excluded.condition_notes,
      nutritional_highlights = excluded.nutritional_highlights,
      updated_at = now();

insert into public.products (
      id, name, brand, slug, category_id, store_id, description, unit, images,
      original_price, base_discount_percent, date_type, expiry_date, listed_at,
      drift_rate_weekly, stock_quantity, featured, storage_condition,
      nafdac_reg_no, condition_notes, nutritional_highlights
    ) values (
      'sg_prod_012', 'Zartech Premium Farm Fresh Whole Chicken (Frozen)', 'Zartech', 'zartech-frozen-whole-chicken-1-3kg',
      'cat_frozen', 'store_market_square', 'Dressed, cleaned, and blast-frozen premium Nigerian poultry. Hormone-free, juicy, and ideal for roasting, pepper soup, or grilling.',
      '1.3kg Whole Bird', ARRAY['https://images.unsplash.com/photo-1587593810167-a84920ea0781?auto=format&fit=crop&w=800&q=80']::text[], 8900,
      45, 'use_by', '2026-09-07',
      '2026-08-08', 0.025, 7,
      true, 'frozen', '01-8840',
      'Maintained at -18°C in Market Square deep freeze.', ARRAY['100% Grain Fed', 'High Protein', 'No Added Water']::text[]
    )
    on conflict (id) do update set
      name = excluded.name,
      brand = excluded.brand,
      slug = excluded.slug,
      category_id = excluded.category_id,
      store_id = excluded.store_id,
      description = excluded.description,
      unit = excluded.unit,
      images = excluded.images,
      original_price = excluded.original_price,
      base_discount_percent = excluded.base_discount_percent,
      date_type = excluded.date_type,
      expiry_date = excluded.expiry_date,
      listed_at = excluded.listed_at,
      drift_rate_weekly = excluded.drift_rate_weekly,
      stock_quantity = excluded.stock_quantity,
      featured = excluded.featured,
      storage_condition = excluded.storage_condition,
      nafdac_reg_no = excluded.nafdac_reg_no,
      condition_notes = excluded.condition_notes,
      nutritional_highlights = excluded.nutritional_highlights,
      updated_at = now();

insert into public.products (
      id, name, brand, slug, category_id, store_id, description, unit, images,
      original_price, base_discount_percent, date_type, expiry_date, listed_at,
      drift_rate_weekly, stock_quantity, featured, storage_condition,
      nafdac_reg_no, condition_notes, nutritional_highlights
    ) values (
      'sg_prod_013', 'Gino Magic Seasoning Curry & Thyme Herbal Blend', 'Gino', 'gino-magic-seasoning-blend-pack',
      'cat_condiments', 'store_h_medix', 'Aromatic blend of turmeric, dried coriander, thyme leaves, and garlic flakes. Adds authentic Nigerian jollof & stew vibrancy.',
      '400g Jar', ARRAY['https://images.unsplash.com/photo-1596040033229-a9821ebd058d?auto=format&fit=crop&w=800&q=80']::text[], 2800,
      30, 'best_before', '2026-09-28',
      '2026-08-20', 0.025, 15,
      false, 'ambient', '01-6543',
      'Dry spice jar with foil induction seal.', ARRAY['Natural Herbs', 'No Preservatives']::text[]
    )
    on conflict (id) do update set
      name = excluded.name,
      brand = excluded.brand,
      slug = excluded.slug,
      category_id = excluded.category_id,
      store_id = excluded.store_id,
      description = excluded.description,
      unit = excluded.unit,
      images = excluded.images,
      original_price = excluded.original_price,
      base_discount_percent = excluded.base_discount_percent,
      date_type = excluded.date_type,
      expiry_date = excluded.expiry_date,
      listed_at = excluded.listed_at,
      drift_rate_weekly = excluded.drift_rate_weekly,
      stock_quantity = excluded.stock_quantity,
      featured = excluded.featured,
      storage_condition = excluded.storage_condition,
      nafdac_reg_no = excluded.nafdac_reg_no,
      condition_notes = excluded.condition_notes,
      nutritional_highlights = excluded.nutritional_highlights,
      updated_at = now();

insert into public.products (
      id, name, brand, slug, category_id, store_id, description, unit, images,
      original_price, base_discount_percent, date_type, expiry_date, listed_at,
      drift_rate_weekly, stock_quantity, featured, storage_condition,
      nafdac_reg_no, condition_notes, nutritional_highlights
    ) values (
      'sg_prod_014', 'Quaker Quick Cooking White Rolled Oats', 'Quaker', 'quaker-quick-cooking-rolled-oats-1kg',
      'cat_pantry', 'store_grand_square', '100% whole grain Canadian oats that cook in just 3 minutes. Rich in beta-glucan soluble fiber to help lower cholesterol.',
      '1kg Tub', ARRAY['https://images.unsplash.com/photo-1586201375761-83865001e31c?auto=format&fit=crop&w=800&q=80']::text[], 5600,
      35, 'best_before', '2026-09-19',
      '2026-08-16', 0.025, 10,
      false, 'ambient', '01-1190',
      'Factory fresh sealed tub.', ARRAY['Heart Healthy Beta-Glucan', '100% Whole Grain', 'Energy Sustaining']::text[]
    )
    on conflict (id) do update set
      name = excluded.name,
      brand = excluded.brand,
      slug = excluded.slug,
      category_id = excluded.category_id,
      store_id = excluded.store_id,
      description = excluded.description,
      unit = excluded.unit,
      images = excluded.images,
      original_price = excluded.original_price,
      base_discount_percent = excluded.base_discount_percent,
      date_type = excluded.date_type,
      expiry_date = excluded.expiry_date,
      listed_at = excluded.listed_at,
      drift_rate_weekly = excluded.drift_rate_weekly,
      stock_quantity = excluded.stock_quantity,
      featured = excluded.featured,
      storage_condition = excluded.storage_condition,
      nafdac_reg_no = excluded.nafdac_reg_no,
      condition_notes = excluded.condition_notes,
      nutritional_highlights = excluded.nutritional_highlights,
      updated_at = now();

insert into public.products (
      id, name, brand, slug, category_id, store_id, description, unit, images,
      original_price, base_discount_percent, date_type, expiry_date, listed_at,
      drift_rate_weekly, stock_quantity, featured, storage_condition,
      nafdac_reg_no, condition_notes, nutritional_highlights
    ) values (
      'sg_prod_015', 'Twinings English Breakfast Pure Black Tea', 'Twinings London', 'twinings-english-breakfast-tea-50bags',
      'cat_beverages', 'store_4u', 'Famous golden and well-rounded master tea blend with body and briskness. 50 individual foil-enveloped tea bags.',
      '50 Tea Bags Box', ARRAY['https://images.unsplash.com/photo-1576092768241-dec231879fc3?auto=format&fit=crop&w=800&q=80']::text[], 4500,
      40, 'best_before', '2026-09-14',
      '2026-08-10', 0.025, 8,
      false, 'ambient', '01-9921',
      'Pristine box condition.', ARRAY['Antioxidant Rich', 'Ethical Tea Partnership']::text[]
    )
    on conflict (id) do update set
      name = excluded.name,
      brand = excluded.brand,
      slug = excluded.slug,
      category_id = excluded.category_id,
      store_id = excluded.store_id,
      description = excluded.description,
      unit = excluded.unit,
      images = excluded.images,
      original_price = excluded.original_price,
      base_discount_percent = excluded.base_discount_percent,
      date_type = excluded.date_type,
      expiry_date = excluded.expiry_date,
      listed_at = excluded.listed_at,
      drift_rate_weekly = excluded.drift_rate_weekly,
      stock_quantity = excluded.stock_quantity,
      featured = excluded.featured,
      storage_condition = excluded.storage_condition,
      nafdac_reg_no = excluded.nafdac_reg_no,
      condition_notes = excluded.condition_notes,
      nutritional_highlights = excluded.nutritional_highlights,
      updated_at = now();

insert into public.products (
      id, name, brand, slug, category_id, store_id, description, unit, images,
      original_price, base_discount_percent, date_type, expiry_date, listed_at,
      drift_rate_weekly, stock_quantity, featured, storage_condition,
      nafdac_reg_no, condition_notes, nutritional_highlights
    ) values (
      'sg_prod_016', 'Golden Penny Semovita Super Fine Wheat', 'Flour Mills of Nigeria', 'golden-penny-semovita-2kg',
      'cat_pantry', 'store_market_square', 'Premium enriched semolina milled from superior quality hard wheat. Smooth, easy to swallow, and molds effortlessly for traditional soups.',
      '2kg Bag', ARRAY['https://images.unsplash.com/photo-1543083477-4f785aeafaa9?auto=format&fit=crop&w=800&q=80']::text[], 4900,
      30, 'best_before', '2026-09-22',
      '2026-08-19', 0.025, 16,
      false, 'ambient', '01-0112',
      'Heavy duty airtight packaging intact.', ARRAY['Fortified with Vitamin A', 'Fiber Rich']::text[]
    )
    on conflict (id) do update set
      name = excluded.name,
      brand = excluded.brand,
      slug = excluded.slug,
      category_id = excluded.category_id,
      store_id = excluded.store_id,
      description = excluded.description,
      unit = excluded.unit,
      images = excluded.images,
      original_price = excluded.original_price,
      base_discount_percent = excluded.base_discount_percent,
      date_type = excluded.date_type,
      expiry_date = excluded.expiry_date,
      listed_at = excluded.listed_at,
      drift_rate_weekly = excluded.drift_rate_weekly,
      stock_quantity = excluded.stock_quantity,
      featured = excluded.featured,
      storage_condition = excluded.storage_condition,
      nafdac_reg_no = excluded.nafdac_reg_no,
      condition_notes = excluded.condition_notes,
      nutritional_highlights = excluded.nutritional_highlights,
      updated_at = now();

insert into public.store_review_scores (store_id, freshness_score, handoff_speed_score, cleanliness_score)
     values ('store_grand_square', 4.9, 4.8, 4.9)
     on conflict (store_id) do update set
       freshness_score = excluded.freshness_score,
       handoff_speed_score = excluded.handoff_speed_score,
       cleanliness_score = excluded.cleanliness_score;

insert into public.store_reviews (
        id, store_id, customer_name, rating, reviewed_on, comment, verified_pickup, user_type
      ) values (
        'rev_1', 'store_grand_square', 'Emeka O.', 5,
        'Yesterday', 'Sent a dispatch rider with my SG order code. The bag was already packed and sealed with cold items chilled. Super seamless!', true, 'Customer'
      )
      on conflict (id) do update set
        store_id = excluded.store_id,
        customer_name = excluded.customer_name,
        rating = excluded.rating,
        reviewed_on = excluded.reviewed_on,
        comment = excluded.comment,
        verified_pickup = excluded.verified_pickup,
        user_type = excluded.user_type;

insert into public.store_reviews (
        id, store_id, customer_name, rating, reviewed_on, comment, verified_pickup, user_type
      ) values (
        'rev_2', 'store_grand_square', 'Rider Ibrahim (Max NG)', 5,
        '3 days ago', 'Very fast pickup at the Stillgood Express desk. Verified the 4-digit code in 30 seconds. No delay for riders.', true, 'Dispatch Rider'
      )
      on conflict (id) do update set
        store_id = excluded.store_id,
        customer_name = excluded.customer_name,
        rating = excluded.rating,
        reviewed_on = excluded.reviewed_on,
        comment = excluded.comment,
        verified_pickup = excluded.verified_pickup,
        user_type = excluded.user_type;

insert into public.store_reviews (
        id, store_id, customer_name, rating, reviewed_on, comment, verified_pickup, user_type
      ) values (
        'rev_3', 'store_grand_square', 'Fatima D.', 4.8,
        'Last week', 'Saved over 45% on Peak milk and brioche buns. Best before dates were exactly as shown on the app.', true, 'Customer'
      )
      on conflict (id) do update set
        store_id = excluded.store_id,
        customer_name = excluded.customer_name,
        rating = excluded.rating,
        reviewed_on = excluded.reviewed_on,
        comment = excluded.comment,
        verified_pickup = excluded.verified_pickup,
        user_type = excluded.user_type;

insert into public.store_review_scores (store_id, freshness_score, handoff_speed_score, cleanliness_score)
     values ('store_h_medix', 4.9, 4.9, 5)
     on conflict (store_id) do update set
       freshness_score = excluded.freshness_score,
       handoff_speed_score = excluded.handoff_speed_score,
       cleanliness_score = excluded.cleanliness_score;

insert into public.store_reviews (
        id, store_id, customer_name, rating, reviewed_on, comment, verified_pickup, user_type
      ) values (
        'rev_4', 'store_h_medix', 'Zainab A.', 5,
        '2 days ago', 'H-Medix Wuse II staff were very polite. The Lurpak butter was kept in deep refrigeration until I arrived.', true, 'Customer'
      )
      on conflict (id) do update set
        store_id = excluded.store_id,
        customer_name = excluded.customer_name,
        rating = excluded.rating,
        reviewed_on = excluded.reviewed_on,
        comment = excluded.comment,
        verified_pickup = excluded.verified_pickup,
        user_type = excluded.user_type;

insert into public.store_reviews (
        id, store_id, customer_name, rating, reviewed_on, comment, verified_pickup, user_type
      ) values (
        'rev_5', 'store_h_medix', 'Rider Samuel (Gokada)', 4.9,
        '4 days ago', 'Quick customer service counter pickup. Code validation works instantly.', true, 'Dispatch Rider'
      )
      on conflict (id) do update set
        store_id = excluded.store_id,
        customer_name = excluded.customer_name,
        rating = excluded.rating,
        reviewed_on = excluded.reviewed_on,
        comment = excluded.comment,
        verified_pickup = excluded.verified_pickup,
        user_type = excluded.user_type;

insert into public.store_review_scores (store_id, freshness_score, handoff_speed_score, cleanliness_score)
     values ('store_next_cash_carry', 4.7, 4.6, 4.8)
     on conflict (store_id) do update set
       freshness_score = excluded.freshness_score,
       handoff_speed_score = excluded.handoff_speed_score,
       cleanliness_score = excluded.cleanliness_score;

insert into public.store_reviews (
        id, store_id, customer_name, rating, reviewed_on, comment, verified_pickup, user_type
      ) values (
        'rev_6', 'store_next_cash_carry', 'Chidi N.', 5,
        '5 days ago', 'Entrance B pickup was so organized. Nutella jar in pristine condition at 45% off retail.', true, 'Customer'
      )
      on conflict (id) do update set
        store_id = excluded.store_id,
        customer_name = excluded.customer_name,
        rating = excluded.rating,
        reviewed_on = excluded.reviewed_on,
        comment = excluded.comment,
        verified_pickup = excluded.verified_pickup,
        user_type = excluded.user_type;

insert into public.store_review_scores (store_id, freshness_score, handoff_speed_score, cleanliness_score)
     values ('store_4u', 4.8, 4.7, 4.7)
     on conflict (store_id) do update set
       freshness_score = excluded.freshness_score,
       handoff_speed_score = excluded.handoff_speed_score,
       cleanliness_score = excluded.cleanliness_score;

insert into public.store_reviews (
        id, store_id, customer_name, rating, reviewed_on, comment, verified_pickup, user_type
      ) values (
        'rev_7', 'store_4u', 'Amina K.', 5,
        '3 days ago', 'Sent my rider to 4U in Wuse II. Smooth handoff with the manager.', true, 'Customer'
      )
      on conflict (id) do update set
        store_id = excluded.store_id,
        customer_name = excluded.customer_name,
        rating = excluded.rating,
        reviewed_on = excluded.reviewed_on,
        comment = excluded.comment,
        verified_pickup = excluded.verified_pickup,
        user_type = excluded.user_type;

insert into public.store_review_scores (store_id, freshness_score, handoff_speed_score, cleanliness_score)
     values ('store_sahad', 4.8, 4.7, 4.8)
     on conflict (store_id) do update set
       freshness_score = excluded.freshness_score,
       handoff_speed_score = excluded.handoff_speed_score,
       cleanliness_score = excluded.cleanliness_score;

insert into public.store_reviews (
        id, store_id, customer_name, rating, reviewed_on, comment, verified_pickup, user_type
      ) values (
        'rev_8', 'store_sahad', 'Bello M.', 5,
        '6 days ago', 'Milo and Titus sardines well packed. Ground floor counter is easy to find.', true, 'Customer'
      )
      on conflict (id) do update set
        store_id = excluded.store_id,
        customer_name = excluded.customer_name,
        rating = excluded.rating,
        reviewed_on = excluded.reviewed_on,
        comment = excluded.comment,
        verified_pickup = excluded.verified_pickup,
        user_type = excluded.user_type;

insert into public.store_review_scores (store_id, freshness_score, handoff_speed_score, cleanliness_score)
     values ('store_market_square', 4.9, 4.8, 4.9)
     on conflict (store_id) do update set
       freshness_score = excluded.freshness_score,
       handoff_speed_score = excluded.handoff_speed_score,
       cleanliness_score = excluded.cleanliness_score;

insert into public.store_reviews (
        id, store_id, customer_name, rating, reviewed_on, comment, verified_pickup, user_type
      ) values (
        'rev_9', 'store_market_square', 'Kelechi U.', 5,
        'Yesterday', 'Frozen Zartech chicken was rock solid frozen upon collection. Very impressed with the cold storage.', true, 'Customer'
      )
      on conflict (id) do update set
        store_id = excluded.store_id,
        customer_name = excluded.customer_name,
        rating = excluded.rating,
        reviewed_on = excluded.reviewed_on,
        comment = excluded.comment,
        verified_pickup = excluded.verified_pickup,
        user_type = excluded.user_type;
