import fs from "node:fs";
import path from "node:path";
import { getCatalogSeed } from "../src/lib/data";

function sqlStr(value: string): string {
  return `'${value.replace(/'/g, "''")}'`;
}

function sqlNullable(value: string | undefined | null): string {
  return value ? sqlStr(value) : "null";
}

function sqlTextArray(values: string[] | undefined): string {
  if (!values || values.length === 0) return `'{}'::text[]`;
  return `ARRAY[${values.map(sqlStr).join(", ")}]::text[]`;
}

function sqlNum(value: number): string {
  return String(value);
}

function sqlBool(value: boolean): string {
  return value ? "true" : "false";
}

const seed = getCatalogSeed();
const lines: string[] = [
  "-- Generated by `npm run db:generate-seed` from src/lib/data.ts.",
  "-- Do not edit by hand. Safe to re-run: uses ON CONFLICT DO UPDATE.",
  "",
];

for (const store of seed.stores) {
  lines.push(
    `insert into public.stores (
      id, name, slug, area, address, phone, rating, review_count,
      open_hours, pickup_instructions, image_url, banner_image_url, lat, lng, is_active
    ) values (
      ${sqlStr(store.id)}, ${sqlStr(store.name)}, ${sqlStr(store.slug)}, ${sqlStr(store.area)},
      ${sqlStr(store.address)}, ${sqlStr(store.phone)}, ${sqlNum(store.rating)}, ${sqlNum(store.reviewCount)},
      ${sqlStr(store.openHours)}, ${sqlStr(store.pickupInstructions)}, ${sqlStr(store.image)},
      ${sqlNullable(store.bannerImage)}, ${sqlNum(store.coordinates.lat)}, ${sqlNum(store.coordinates.lng)},
      ${sqlBool(store.isActive)}
    )
    on conflict (id) do update set
      name = excluded.name,
      slug = excluded.slug,
      area = excluded.area,
      address = excluded.address,
      phone = excluded.phone,
      rating = excluded.rating,
      review_count = excluded.review_count,
      open_hours = excluded.open_hours,
      pickup_instructions = excluded.pickup_instructions,
      image_url = excluded.image_url,
      banner_image_url = excluded.banner_image_url,
      lat = excluded.lat,
      lng = excluded.lng,
      is_active = excluded.is_active,
      updated_at = now();`
  );
  lines.push("");
}

for (const category of seed.categories) {
  lines.push(
    `insert into public.categories (
      id, name, slug, icon, description, item_count, gradient, bg_light
    ) values (
      ${sqlStr(category.id)}, ${sqlStr(category.name)}, ${sqlStr(category.slug)}, ${sqlStr(category.icon)},
      ${sqlStr(category.description)}, ${sqlNum(category.itemCount)}, ${sqlStr(category.gradient)},
      ${sqlStr(category.bgLight)}
    )
    on conflict (id) do update set
      name = excluded.name,
      slug = excluded.slug,
      icon = excluded.icon,
      description = excluded.description,
      item_count = excluded.item_count,
      gradient = excluded.gradient,
      bg_light = excluded.bg_light;`
  );
  lines.push("");
}

for (const product of seed.products) {
  lines.push(
    `insert into public.products (
      id, name, brand, slug, category_id, store_id, description, unit, images,
      original_price, base_discount_percent, date_type, expiry_date, listed_at,
      drift_rate_weekly, stock_quantity, featured, storage_condition,
      nafdac_reg_no, condition_notes, nutritional_highlights
    ) values (
      ${sqlStr(product.id)}, ${sqlStr(product.name)}, ${sqlStr(product.brand)}, ${sqlStr(product.slug)},
      ${sqlStr(product.category)}, ${sqlStr(product.storeId)}, ${sqlStr(product.description)},
      ${sqlStr(product.unit)}, ${sqlTextArray(product.images)}, ${sqlNum(product.originalPrice)},
      ${sqlNum(product.baseDiscountPercent)}, ${sqlStr(product.dateType)}, ${sqlStr(product.expiryDate)},
      ${sqlStr(product.listedAt)}, ${sqlNum(product.driftRateWeekly ?? 0.025)}, ${sqlNum(product.stockQuantity)},
      ${sqlBool(product.featured)}, ${sqlStr(product.storageCondition)}, ${sqlNullable(product.nafdacRegNo)},
      ${sqlNullable(product.conditionNotes)}, ${sqlTextArray(product.nutritionalHighlights)}
    )
    on conflict (id) do update set
      name = excluded.name,
      brand = excluded.brand,
      slug = excluded.slug,
      category_id = excluded.category_id,
      store_id = excluded.store_id,
      description = excluded.description,
      unit = excluded.unit,
      images = excluded.images,
      original_price = excluded.original_price,
      base_discount_percent = excluded.base_discount_percent,
      date_type = excluded.date_type,
      expiry_date = excluded.expiry_date,
      listed_at = excluded.listed_at,
      drift_rate_weekly = excluded.drift_rate_weekly,
      stock_quantity = excluded.stock_quantity,
      featured = excluded.featured,
      storage_condition = excluded.storage_condition,
      nafdac_reg_no = excluded.nafdac_reg_no,
      condition_notes = excluded.condition_notes,
      nutritional_highlights = excluded.nutritional_highlights,
      updated_at = now();`
  );
  lines.push("");
}

for (const [storeId, data] of Object.entries(seed.reviews)) {
  lines.push(
    `insert into public.store_review_scores (store_id, freshness_score, handoff_speed_score, cleanliness_score)
     values (${sqlStr(storeId)}, ${sqlNum(data.freshnessScore)}, ${sqlNum(data.handoffSpeedScore)}, ${sqlNum(data.cleanlinessScore)})
     on conflict (store_id) do update set
       freshness_score = excluded.freshness_score,
       handoff_speed_score = excluded.handoff_speed_score,
       cleanliness_score = excluded.cleanliness_score;`
  );
  lines.push("");
  for (const review of data.reviews) {
    lines.push(
      `insert into public.store_reviews (
        id, store_id, customer_name, rating, reviewed_on, comment, verified_pickup, user_type
      ) values (
        ${sqlStr(review.id)}, ${sqlStr(storeId)}, ${sqlStr(review.customerName)}, ${sqlNum(review.rating)},
        ${sqlStr(review.date)}, ${sqlStr(review.comment)}, ${sqlBool(review.verifiedPickup)}, ${sqlStr(review.userType)}
      )
      on conflict (id) do update set
        store_id = excluded.store_id,
        customer_name = excluded.customer_name,
        rating = excluded.rating,
        reviewed_on = excluded.reviewed_on,
        comment = excluded.comment,
        verified_pickup = excluded.verified_pickup,
        user_type = excluded.user_type;`
    );
    lines.push("");
  }
}

const outPath = path.join(process.cwd(), "supabase", "seed.sql");
fs.writeFileSync(outPath, `${lines.join("\n").trim()}\n`);
console.log(`Wrote ${outPath}`);
